/*
 * Script used to read a css file, get the css vars and make it into a js object
 */

const path = require("path");
const fs = require("fs/promises");

async function main() {
  // Get command line arguments
  const args = process.argv.slice(2);

  if (args.length < 2) {
    console.error("Usage: node script.js <css-file-path> <output-file-path>");
    process.exit(1);
  }

  const cssFilePath = path.resolve(args[0]);
  const outputFilePath = path.resolve(args[1]);

  try {
    // Read the CSS file
    const cssContent = await fs.readFile(cssFilePath, "utf-8");

    // Extract CSS variables using regex
    // Matches --variable-name: value; patterns
    const cssVarRegex = /--([a-zA-Z0-9-_]+)\s*:\s*([^;]+);/g;
    const cssVars = {};

    let match;
    while ((match = cssVarRegex.exec(cssContent)) !== null) {
      const varName = match[1];
      const varValue = match[2].trim();
      cssVars[varName] = varValue;
    }

    // Generate JavaScript content
    const jsContent = `// Auto-generated from ${path.basename(cssFilePath)}
// Generated on ${new Date().toISOString()}
// Generated by cssVarToJsObject.js

export const cssVariables = ${JSON.stringify(cssVars, null, 2)};
`;

    // Write to output file
    await fs.writeFile(outputFilePath, jsContent, "utf-8");

    console.log(
      `✓ Successfully extracted ${Object.keys(cssVars).length} CSS variables`,
    );
    console.log(`✓ Output written to: ${outputFilePath}`);
  } catch (error) {
    console.error("Error:", error.message);
    process.exit(1);
  }
}

main();
