name: Test Release Upload

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # Allows creating/updating releases

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create example file
        run: echo "Hello! This is a test release." > example-file.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: example-file.txt