name: Release fluf-linux-x64 

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write 

jobs:
  build-release-fluf-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install UI Dependencies
        run: npm i
        working-directory: ./ui

      - name: Install Desktop Dependencies
        run: npm i
        working-directory: ./desktop

      - name: Install Build Tool Dependencies
        run: npm i
        working-directory: ./build

      - name: Final Build Execution
        run: npm run build
        working-directory: ./build

      - name: Create tar.gz Archive
        run: tar -czf fluf-linux-x64.tar.gz -C stage_three .
        working-directory: "./build/build-output"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./build/build-output/fluf-linux-x64.tar.gz